apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-deploy
  labels:
    app: fitness
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fitness
  template:
    metadata:
      labels:
        app: fitness
    spec:
      containers:
        - name: fitness-tracker
          image: angira9/fitness-tracker:latest
          ports:
            - containerPort: 3000
